- name: cloud_config | create
  template:
    dest: "{{ libvirt_images_path }}/{{ libvirt_result_domain_name }}.cloud-config"
    src: "cloud-config.yml.j2"
  register: libvirt_create_cloud_config_result

- name: cloud_config | create image
  command: >
    cloud-localds
    {{ libvirt_result_domain_name }}.cloud-config.img
    {{ libvirt_result_domain_name }}.cloud-config
  args:
    chdir: "{{ libvirt_images_path }}"
  when: libvirt_create_cloud_config_result.changed