---

- name: list all domain names
  command: virsh list --all --name
  changed_when: no
  register: libvirt_list_all_result

- name: extract all domain names
  set_fact:
    libvirt_all_domains: "{{ libvirt_list_all_result.stdout_lines }}"
  when: not ansible_check_mode

- name: shutdown
  shell: >
    virsh shutdown "{{ item }}";
    while virsh list | grep -q -F " {{ item }} "; do
      sleep 2
    done
  register: libvirt_machine_shutdown_result
  until: libvirt_machine_shutdown_result.rc == 0
  with_items: "{{ to_destroy }}"
  when: not ansible_check_mode

- name: undefine machine
  command: 'virsh undefine "{{ item }}"'
  when: not ansible_check_mode and (item in libvirt_all_domains)
  with_items: "{{ to_destroy }}"

- name: delete images
  shell: 'rm -rf {{ item }}.*'
  args:
    chdir: "{{ libvirt_images_path }}"
    removes: "{{ libvirt_images_path }}/{{ item }}.img"
  with_items: "{{ to_destroy }}"
