---
- name: Ensure image path exists
  file:
    path: "{{ image_download_path }}"
    state: directory
    recurse: yes

- name: Check if image is already downloaded
  stat:
    path: "{{ image_download_path }}/{{ libvirt_images_image_dist }}"
  register: check

- block:
  - name: download image disk
    get_url:
      url: "{{ url }}"
      dest: "{{ image_download_path }}/{{ libvirt_images_image_dist }}"
    register: libvirt_images_download_result

  - name: remove modified image
    file:
      path: "{{ image_download_path }}/{{ libvirt_images_image_name }}"
      state: absent
    when: libvirt_images_download_result.changed

  - name: convert the image
    command: "qemu-img convert -O qcow2 {{ libvirt_images_image_dist }} {{ libvirt_images_image_name }}"
    args:
      chdir: "{{ image_download_path }}"
      creates: "{{ libvirt_images_path }}/{{ libvirt_images_image_name }}"
  when: check.stat.exists == False

