---

- name: Setup Host
  include_tasks: setup_host.yml
  when: state == 'setup' or state == 'install'

- name: Setup Network
  include_tasks: network.yml
  when: state == 'network' or state == 'install'

- name: Download Image
  include_tasks: image.yml
  when: state == 'create'

- name: Creating Machine
  include_tasks: machine.yml
  when: state == 'create'

- name: Destroy Machine
  include_tasks: destroy.yml
  when: state == 'destroy'