---
- name: Ensure image path exists
  file:
    path: "{{ libvirt_images_path }}"
    state: directory
    recurse: yes

- name: download image disk
  get_url:
    url: "{{ libvirt_images_ubuntu_cloud_image_url }}"
    dest: "{{ libvirt_images_path }}/{{ libvirt_images_ubuntu_cloud_image_dist }}"
  register: libvirt_images_ubuntu_cloud_download_result

- name: remove modified image
  file:
    path: "{{ libvirt_images_path }}/{{ libvirt_images_ubuntu_cloud_image_name }}"
    state: absent
  when: libvirt_images_ubuntu_cloud_download_result.changed

- name: convert the image
  command: "qemu-img convert -O qcow2 {{ libvirt_images_ubuntu_cloud_image_dist }} {{ libvirt_images_ubuntu_cloud_image_name }}"
  args:
    chdir: "{{ libvirt_images_path }}"
    creates: "{{ libvirt_images_path }}/{{ libvirt_images_ubuntu_cloud_image_name }}"

- include: store_facts.yml
  when: libvirt_images_ubuntu_cloud_download_result.changed
